# Generated by Django 2.2.1 on 2019-05-20 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageOwnerByTokenUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('uid', models.CharField(max_length=50)),
                ('likes', models.IntegerField()),
                ('profile_picture_link', models.CharField(max_length=255)),
                ('profile_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TokenPageManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_page_manager', models.CharField(max_length=255)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokenspagemanager', to='pagetools.PageOwnerByTokenUser')),
            ],
        ),
        migrations.CreateModel(
            name='TokenUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=255)),
                ('is_logged_in', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokensadded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TokenUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('uid', models.CharField(max_length=50)),
                ('profile_picture_link', models.CharField(max_length=255)),
                ('profile_link', models.CharField(max_length=255)),
                ('token_user', models.OneToOneField(blank=True, null=True, on_delete='SET_NULL', to='pagetools.TokenUser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TokenPageManagerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('uid', models.CharField(max_length=50)),
                ('profile_picture_link', models.CharField(max_length=255)),
                ('profile_link', models.CharField(max_length=255)),
                ('token_page_manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pagetools.TokenPageManager')),
            ],
        ),
        migrations.AddField(
            model_name='tokenpagemanager',
            name='token_user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokenspagemanager', to='pagetools.TokenUserProfile'),
        ),
        migrations.AddField(
            model_name='pageownerbytokenuser',
            name='token_user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='pagetools.TokenUserProfile'),
        ),
        migrations.CreateModel(
            name='PageAccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_access_token', models.CharField(max_length=255)),
                ('token_page_manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pagetools.TokenPageManager')),
            ],
        ),
        migrations.CreateModel(
            name='ContentSendInbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='pagetools.PageOwnerByTokenUser')),
            ],
        ),
    ]
