# Generated by Django 2.2.1 on 2019-05-21 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagetools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageownerbytokenuser',
            name='token_user_profile',
        ),
        migrations.AddField(
            model_name='pageownerbytokenuser',
            name='token_user_profile',
            field=models.ManyToManyField(to='pagetools.TokenUserProfile'),
        ),
        migrations.AlterField(
            model_name='tokenuserprofile',
            name='token_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagetools.TokenUser'),
        ),
    ]
