# Generated by Django 2.2.1 on 2019-05-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagetools', '0003_auto_20190526_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageownerbytokenuser',
            name='token_user_profile',
            field=models.ManyToManyField(blank=True, null=True, related_name='pages', to='pagetools.TokenUserProfile'),
        ),
    ]
