# Generated by Django 2.2.1 on 2019-05-27 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagetools', '0004_auto_20190526_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageownerbytokenuser',
            name='token_user_profile',
            field=models.ManyToManyField(blank=True, related_name='pages', to='pagetools.TokenUserProfile'),
        ),
        migrations.CreateModel(
            name='DataUIDOfPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(max_length=100)),
                ('uid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=20)),
                ('last_updated', models.DateField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='pagetools.PageOwnerByTokenUser')),
            ],
        ),
    ]
