# Generated by Django 2.2.1 on 2019-06-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagetools', '0005_auto_20190527_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsendinbox',
            name='image',
            field=models.ImageField(default='none', upload_to='image_send_inbox'),
        ),
    ]
