# Generated by Django 2.2.1 on 2019-06-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagetools', '0006_contentsendinbox_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentsendinbox',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_send_inbox'),
        ),
    ]
